services:
  postgres:
    image: postgres:17
    container_name: db-sec-lab-7
    restart: unless-stopped

    environment:
      POSTGRES_USER: stan
      POSTGRES_DB: lab_7
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Europe/Amsterdam

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-archive:/var/lib/postgresql/archive
      - ./pg-backups:/backups

    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - archive_mode=on
      - -c
      - archive_command=test ! -f /var/lib/postgresql/archive/%f && cp %p /var/lib/postgresql/archive/%f
      - -c
      - archive_timeout=30s
      - -c
      - checkpoint_timeout=5min
      - -c
      - max_wal_size=1GB
      - -c
      - min_wal_size=80MB
      - -c
      - checkpoint_completion_target=0.9

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stan -d lab_7"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
