services:
  postgres:
    image: postgres:17
    container_name: db-sec-lab-7
    restart: unless-stopped
    environment:
      POSTGRES_USER: stan
      POSTGRES_DB: lab_7
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Europe/Amsterdam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stan -d lab_7"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
